### ISSUE TITLE
npm not found after updating images

### ISSUE THREAD

**Issue by zaifastafa** [shyim/shopware-docker#103]
**Describe the bug**
./modules/platform/admin-build.sh: line 20: npm: command not found

**To Reproduce**
- git pull
- swdc update-images
- swdc admin-build sw6

**Expected behavior**
build completes successfully. 

**Environment:**
 - OS: Ubuntu 20.04

**Comment by shyim** [comment]
Can you stop swdc and run docker volume rm shopware-docker_nvm_cache

**Comment by zaifastafa** [comment]
Did, but the issue persists. New volume is created `Creating volume "shopware-docker_nvm_cache" with local driver after swdc up
`

**Comment by shyim** [comment]
Can you try to run
bash /usr/local/bin/setup_nvm

**Comment by zaifastafa** [comment]
Inside the container?

**Comment by zaifastafa** [comment]
Nothing happens

![image](https://user-images.githubusercontent.com/24492269/124443507-2c6be200-dd97-11eb-9104-157e18b4d225.png)

**Comment by shyim** [comment]
does node / npm work in swdc shell?

**Comment by zaifastafa** [comment]
nope. command not found.

**Comment by shyim** [comment]
Okay its broken at me too. I will look...

**Comment by shyim** [comment]
Pull now again. Should be fixed in newer images as 7.3

**Comment by zaifastafa** [comment]
Hey, I pulled, did remove the nvm volume, did update the images and then did admin-build again, but the problem is still there

**Comment by zaifastafa** [comment]
the node and npm are there in the shell now, but the admin-build still cannot find the command.

**Comment by zaifastafa** [comment]
OK for some reason it worked when I tried again right now.
